name: GitHub Push on Main Branch

on:
  push:
    branches:
    - main

jobs:
  generate-docker-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id_token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Log in DockerHub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: faustyx/e89-devops-projects

      - name: Get Dockerfile
        run: |
          sudo mkdir /docker_checking
          sudo git clone https://github.com/devops-ecole89/Nathan_Docker_CI-CD.git /docker_checking/

      - name: Build & Push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: /docker_checking/Dockerfile_Main
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
