name: GitHub Push on Main Branch

### Action trigger on push on the main branch
on:
  push:
    branches:
    - main

### Use the latest version of ubuntu
jobs:
  generate-docker-image:
    runs-on: ubuntu-latest
    ### Add permissions for the process
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      ### Set up git global config for git command
      - name: Set up git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      ### Try to log to Docker Hub with secrets user & pass
      - name: Log in DockerHub
#        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      ### Get the metadata of the actual docker hub repo 
      - name: Extract metadata (tags, labels) for Docker
        id: meta
#        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        uses: docker/metadata-action@v3
        with:
          images: faustyx/e89-devops-projects

      ### Get the Dockerfile to push
      - name: Get Dockerfile
        run: |
          sudo mkdir /docker_checking
          sudo git clone https://github.com/devops-ecole89/Nathan_Docker_CI-CD.git /docker_checking/

      ### Build and Push the docker image
      - name: Build & Push Docker image
        id: push
        uses: docker/build-push-action@v6
#        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: /docker_checking/Dockerfile_Main
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
